[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
    # panics in ring
    "RUSTSEC-2025-0009", # we don't enable overflow-checks in release

    # proc-macro-error is unmaintained
    "RUSTSEC-2024-0370", # TODO: upgrade or replace utoipa

    # sqlx has overflow vulnerability
    "RUSTSEC-2024-0363", # the size limit of request bodies prevent this

    # paste is unmaintained
    "RUSTSEC-2024-0436", # it is a tiny macro utility only used rmp internally and works for them
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "MPL-2.0",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "LicenseRef-ring",
    "Apache-2.0 WITH LLVM-exception",
    "AGPL-3.0",
    "Unicode-3.0",
]

# Exception for rings license
[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]
