services:
  nginx:
    restart: unless-stopped
    depends_on: [ webserver ]
    networks: [ net-kraken ]
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./data/conf/nginx/kraken.conf:/etc/nginx/conf.d/default.conf:ro
    build:
      dockerfile: ./build/dockerfiles/nginx.Dockerfile

  webserver:
    labels:
      - webserver
    restart: unless-stopped
    depends_on: [ postgres ]
    networks: [ net-kraken ]
    volumes:
      - kraken-vol:/var/lib/kraken
    env_file: [ .env ]
    ports:
      - "31337:31337"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
    build:
      dockerfile: ./build/dockerfiles/webserver.Dockerfile

  postgres:
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    networks: [ net-kraken ]
    volumes:
      - postgres-vol:/var/lib/postgresql/data/
    env_file: [ .env ]
    build:
      dockerfile: ./build/dockerfiles/postgres.Dockerfile


networks:
  net-kraken:
    driver: bridge

volumes:
  kraken-vol:
  postgres-vol:
