services:
  webserver-dev:
    labels:
      - webserver
    restart: unless-stopped
    depends_on: [ postgres-dev ]
    networks: [ net-kraken ]
    volumes:
      - kraken-vol:/var/lib/kraken
      - kraken-logs-vol:/var/log/kraken
      - ./kraken/migrations:/migrations
    env_file: [ .env ]
    environment:
      - POSTGRES_HOST=postgres-dev
      - POSTGRES_PORT=5432
      - POSTGRES_DB=kraken
      - POSTGRES_USER=kraken
      - POSTGRES_PASSWORD=password
    user: "${UID}:${GID}"
    image: registry:443/kraken-dev/webserver:${DEV_TAG}
    build:
      dockerfile: ./build/dockerfiles/webserver-dev.Dockerfile

  postgres-dev:
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    networks: [ net-kraken ]
    volumes:
      - postgres-vol:/var/lib/postgresql/data/
    env_file: [ .env ]
    environment:
      - POSTGRES_HOST=postgres-dev
      - POSTGRES_PORT=5432
      - POSTGRES_DB=kraken
      - POSTGRES_USER=kraken
      - POSTGRES_PASSWORD=password
    image: registry:443/kraken-dev/postgres:${DEV_TAG}
    build:
      dockerfile: ./build/dockerfiles/postgres.Dockerfile

networks:
  net-kraken:
    driver: bridge

volumes:
  postgres-vol:
    name: ${COMPOSE_PROJECT_NAME}-postgres-vol-${DEV_TAG}
  kraken-vol:
  kraken-logs-vol:
