[Migration]
Hash = ""
Initial = false
Dependency = 1
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "dnstxtscanresult"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "domain"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "rule"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "txt_type"
Type = "choices"

[[Migration.Operations.Fields.Annotations]]
Type = "choices"
Value = [
    "HasGoogleAccount",
    "HasGlobalsignAccount",
    "HasGlobalsignSMime",
    "HasDocusignAccount",
    "HasAppleAccount",
    "HasFacebookAccount",
    "HasHubspotAccount",
    "HasMSDynamics365",
    "HasStripeAccount",
    "HasOneTrustSso",
    "HasBrevoAccount",
    "OwnsAtlassianAccounts",
    "OwnsZoomAccounts",
    "EmailProtonMail",
    "SpfAll",
    "SpfInclude",
    "SpfA",
    "SpfMx",
    "SpfPtr",
    "SpfIp",
    "SpfExists",
    "SpfRedirect",
    "SpfExplanation",
    "SpfModifier",
]

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "spf_ip"
Type = "ipnetwork"
Annotations = []

[[Migration.Operations.Fields]]
Name = "spf_domain"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields]]
Name = "spf_domain_ipv4_cidr"
Type = "int32"
Annotations = []

[[Migration.Operations.Fields]]
Name = "spf_domain_ipv6_cidr"
Type = "int32"
Annotations = []

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "dnstxtscanresult"

[Migration.Operations.Field]
Name = "attack"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "attack"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "RawSQL"
StructureSafe = true
SQLite = "only Postgres databases are supported right now"
MySQL = "only Postgres databases are supported right now"
Postgres = "ALTER TYPE _attack_attack_type ADD VALUE IF NOT EXISTS 'DnsTxtScan' AFTER 'DnsResolution';"

[[Migration.Operations]]
Type = "RawSQL"
StructureSafe = true
SQLite = "only Postgres databases are supported right now"
MySQL = "only Postgres databases are supported right now"
Postgres = "ALTER TYPE _aggregationsource_source_type ADD VALUE IF NOT EXISTS 'DnsTxtScan' AFTER 'DnsResolution';"

[[Migration.Operations]]
Type = "RawSQL"
StructureSafe = true
SQLite = "only Postgres databases are supported right now"
MySQL = "only Postgres databases are supported right now"
Postgres = "ALTER TYPE _searchresult_ref_type ADD VALUE IF NOT EXISTS 'DnsTxtScanResult' AFTER 'DnsRecordResult';"


