[Migration]
Hash = "2862079668694153915"
Initial = false
Dependency = 2
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "dnstxtscanattackresult"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "domain"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "collection_type"
Type = "choices"

[[Migration.Operations.Fields.Annotations]]
Type = "choices"
Value = [
    "ServiceHints",
    "Spf",
]

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateModel"
Name = "dnstxtscanservicehintentry"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "rule"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "txt_type"
Type = "choices"

[[Migration.Operations.Fields.Annotations]]
Type = "choices"
Value = [
    "HasGoogleAccount",
    "HasGlobalsignAccount",
    "HasGlobalsignSMime",
    "HasDocusignAccount",
    "HasAppleAccount",
    "HasFacebookAccount",
    "HasHubspotAccount",
    "HasMSDynamics365",
    "HasStripeAccount",
    "HasOneTrustSso",
    "HasBrevoAccount",
    "OwnsAtlassianAccounts",
    "OwnsZoomAccounts",
    "EmailProtonMail",
]

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateModel"
Name = "dnstxtscanspfentry"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[[Migration.Operations.Fields]]
Name = "rule"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "spf_type"
Type = "choices"

[[Migration.Operations.Fields.Annotations]]
Type = "choices"
Value = [
    "All",
    "Include",
    "A",
    "Mx",
    "Ptr",
    "Ip",
    "Exists",
    "Redirect",
    "Explanation",
    "Modifier",
]

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations.Fields]]
Name = "spf_ip"
Type = "ipnetwork"
Annotations = []

[[Migration.Operations.Fields]]
Name = "spf_domain"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields]]
Name = "spf_domain_ipv4_cidr"
Type = "int32"
Annotations = []

[[Migration.Operations.Fields]]
Name = "spf_domain_ipv6_cidr"
Type = "int32"
Annotations = []

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "dnstxtscanattackresult"

[Migration.Operations.Field]
Name = "attack"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "attack"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "dnstxtscanspfentry"

[Migration.Operations.Field]
Name = "collection"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "dnstxtscanattackresult"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "CreateField"
Model = "dnstxtscanservicehintentry"

[Migration.Operations.Field]
Name = "collection"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "dnstxtscanattackresult"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[[Migration.Operations]]
Type = "DeleteModel"
Name = "dnstxtscanresult"
